### ISSUE TITLE
Host header rewrite

### ISSUE THREAD

**Issue by danydev** [beyondcode/expose#57] opened 2020-06-20 08:51 UTC
First of all, let me say that you did an amazing job! Sometimes is really useful to expose my local environment for a quick test, I usually use Charles acting as proxy or ngrok, but expose will be even better since I can reserve my own subdomain!

Now the problem: when accessing my local environment the host header returned by my webserver is hardcoded, so when I expose with `expose share mywebsite.local.com:443` and then go to https://something.sharedwithexpose.com I correctly see the web page served by my local environment but I get redirected to  https://mywebsite.local.com, this because there is a redirection based in the host header and such header value is https://mywebsite.local.com instead of https://something.sharedwithexpose.com What ngrok offers to overcome this use case is a flag `-host-header=rewrite`.

Quoting their [doc](https://ngrok.com/docs)
```
Rewriting the Host header
When forwarding to a local port, ngrok does not modify the tunneled HTTP requests at all, they are copied to your server byte-for-byte as they are received. Some application servers like WAMP and MAMP and use the Host header for determining which development site to display. For this reason, ngrok can rewrite your requests with a modified Host header. Use the -host-header switch to rewrite incoming HTTP requests.

If rewrite is specified, the Host header will be rewritten to match the hostname portion of the forwarding address. Any other value will cause the Host header to be rewritten to that value.

Rewrite the Host header to 'site.dev'
ngrok http -host-header=rewrite site.dev:80
Rewrite the Host header to 'example.com'
ngrok http -host-header=example.com 80
```

**Comment by aaemnnosttv** [comment] 2020-06-21 17:35
I thought this might be an issue as well, but it seems that this is already happening. When you dump `$_SERVER['HTTP_HOST']` you should see the hostname of the URL you shared.

This looks like the same issue as #24 .

**Comment by danydev** [comment] 2020-06-21 18:12
Not for me, I see `https://mywebsite.local.com` in `HTTP_HOST`

**Comment by mpociot** [comment] 2020-06-24 09:27
Hi @danydev 

We are actually already doing this. Even though the host name can't be configured manually - maybe that would be helpful.
But instead, the hostname gets used when you specify it while sharing:

See https://github.com/beyondcode/expose/blob/e870878bceb84b9f5d8ec6c81bb89078e2489d15/app/Server/Http/Controllers/TunnelMessageController.php#L116

This is the host that you configure when sharing your site.

So `expose share foo.test` will set the host header to `foo.test`.

Could you try and see if it makes a difference for you if you do:

```
expose share https://mysite.test
```

vs

```
expose share mysite.test:443
```

**Comment by danydev** [comment] 2020-06-24 09:50
No difference, I still see the 'wrong' header. But now that you're telling me that the tool should already handle it. I suppose it has something to do with my setup. My dev environment is composed by a traefik container acting as reverse proxy to a nginx container.

Looks like ngrok is able to 'override' somehow the redirection that my application-level code is doing to the correct host. I think it's just because they do some additional work to make it working in those cases.

Note how if I go to a path where there are redirections the website is correctly served, only when there is a 30x I got redirected to the "wrong” local url.

**Comment by mpociot** [comment] 2020-06-24 09:51
Would be interesting to see the headers that ngrok is sending in your specific use case (taken from the local inspector view) compared to what expose is doing.

**Comment by danydev** [comment] 2020-06-24 09:56
Looks like my application-level code always see the 'wrong' header (and that's fine as long as I get redirected to the correct host), so I suppose the 'fix' is done by ngrok while acting as middle-man.

Inspecting the response of the response with a proxy I can tell ngrok response already contains the correct Location/Host headers (`Location: https://bbd708a5e84c.ngrok.io/login`), so I think it's something they do server-side.

Also, not sure if you are asking for something specific.

**Comment by mpociot** [comment] 2020-06-24 10:00
Yeah I would be interested in the headers that you see in the local dashboards when you inspect a specific request (the one at http://127.0.0.1:4040
As they contain the headers that get sent to your expose client - without your application level code being in-between (and any proxied servers)

**Comment by danydev** [comment] 2020-06-24 10:04
```
GET /

Host | myservice.local.it
X-Original-Host | bbd708a5e84f.ngrok.io
```

```
302 Found
Location | https://myservice.local.it/login
```

Now, you may say "well, looks like you should be redirected to myservice.local.it, not really, the curl tells me that 
```
Location: https://bbd708a5e84f.ngrok.io/login
```
indeed I get redirected there (to ngrok.io, not to myservice)

**Comment by mpociot** [comment] 2020-06-24 10:12
Okay great, could you show me the same header results on expose's dashboard?
Just to see if the headers are the same

**Comment by danydev** [comment] 2020-06-24 10:16
```
GET /
Host myservice.local.it:443
x-original-host: xudu45wyce.sharedwithexpose.com
x-forwarded-for: my-ip-address
```
Response
```
Location: https://myservice.local.it/login
```

**Comment by danydev** [comment] 2020-06-24 10:44
By inspecting traefik logs I see one additional header not shown in localhost:4040 tool
```
X-Original-Host: bbd708a5e84c.ngrok.io
```
it may be the trick that makes it happen?

**Comment by Sebastiangperez** [comment] 2020-06-28 15:08
I have the same issue , when i perform a login , redirects to my localdomain with the page expired message.

**Comment by Obvinyg** [comment] 2020-06-29 12:52
I have this issue too.

I wonder if the solution to this SO question will work for this too? https://stackoverflow.com/questions/43490688/ngrok-and-laravel

**Comment by stuba** [comment] 2020-06-30 06:55
Same here. I'm using Pomerium as proxy. I did test Ngork and it did seem to work better in this case, maybe it is working more like a "real proxy" service.

Now I did manage to overcome this problem, just for a sake of testing, with few changes.
- Add xyz.sharedwithexpose.com to your /etc/hosts pointing 127.0.0.1
- Add separate route to my Pomerium config from URL xyz.sharedwithexpose.com
- Add to my Nginx config  'fastcgi_param SERVER_NAME' xyz.sharedwithexpose.com
- My Pomerium requires valid cert so I needed to open xyz.sharedwithexpose.com once and accept failing cert

So most likely all you that have similar problems have a look at your proxies and test connections with curl that Expose dashboard provides to you. That helped me to understand this issue a bit.  I'm not a real proxy wizard and there might much easier solutions for this, like Pomerium preserve_host_header. Of course if Expose could work a bit better on this matter, but I'm not that sure how easily it could be achieved. Maybe there is more clever guys who could provide some good ideas..?

Nice tool overall guys!

**Comment by stuba** [comment] 2020-07-01 08:40
Just as an update for my previous post. Now it all works perfectly. Key was to make sure original URL is passed correctly to application server. So I would not call this a bug, but just thing that might be worth document a bit better.

**Resolution will be up to you setup, how it worked out for me.**
First I had to make sure Pomerium route has preserve_host_header = true. Depending on source my app will receive requested host from header as host or X-Original-Host.  Then it was just a matter of selecting correct host and pass it over to fastcgi.

```
map $http_x_original_host $my_real_host {
    default       $http_x_original_host;
    ''            $http_host;
}
.
.
.
fastcgi_param SERVER_NAME $my_real_host;
fastcgi_param HTTP_HOST   $my_real_host;
```

So now my application will receive host used for original request and it will generate correct URLs depending where requests are coming from and I do not have to modify my application source code at all. Hope this helps somebody to with similar problems.

**Comment by mpociot** [comment] 2020-07-01 16:09
I just added the `X-Forwarded-Host` to expose, so hopefully servers can just make use of this.
Because host header rewrites "just work" based on the site that you share.
Maybe it might be an interesting option to manually specify the host header when sharing a site, but since you share URLs, you can just share the URL that contains the correct hostname.

**Comment by danydev** [comment] 2020-07-02 08:36
Just tested, and it did not solve my problem.

Just to clarify: I could easily fiddle with traefik and headers to fool my web server and make it works, but still would require me make operational changes for the tool, while ngrok works out of the box.

**Comment by tomb1n0** [comment] 2020-10-23 08:12
@danydev did you ever figure out a workaround for this? I love the look of Expose but also using Traefik

**Comment by danydev** [comment] 2020-10-23 08:30
The key is to configure traefik to replace `Host` with `X-Original-Host`. Traefik does not allow dynamic header rewrite (I think it's in the works), but you can still hardcode it.

**Comment by tomb1n0** [comment] 2020-10-23 09:48
@danydev Sorry to ask this - do you have an example of the labels required to make this work please?

**Comment by SleeplessByte** [comment] 2020-11-15 02:19
If I recall correctly, in order for systems such as Laravel, Rails, or reverse proxies etc. to pick this up correctly, it's not only `X-Forwarded-Host` that should be added, but also `X-Forwarded-For` and `X-Forwarded-Proto`. Might as well also add the [`Forwarded`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header.

**Comment by guilhermeagirardi** [comment] 2020-12-28 18:02
> Just as an update for my previous post. Now it all works perfectly. Key was to make sure original URL is passed correctly to application server. So I would not call this a bug, but just thing that might be worth document a bit better.
> 
> **Resolution will be up to you setup, how it worked out for me.**
> First I had to make sure Pomerium route has preserve_host_header = true. Depending on source my app will receive requested host from header as host or X-Original-Host. Then it was just a matter of selecting correct host and pass it over to fastcgi.
> 
> ```
> map $http_x_original_host $my_real_host {
>     default       $http_x_original_host;
>     ''            $http_host;
> }
> .
> .
> .
> fastcgi_param SERVER_NAME $my_real_host;
> fastcgi_param HTTP_HOST   $my_real_host;
> ```
> 
> So now my application will receive host used for original request and it will generate correct URLs depending where requests are coming from and I do not have to modify my application source code at all. Hope this helps somebody to with similar problems.

Very goooood! Thank you! 😃

**Comment by danydev** [comment] 2021-06-08 10:59
I'm not sure it's good to close the issue here. While we can actually fiddle with webserver\proxy parameters to get it right, ngrok doesn't need to do it in order to give the same functionality.

**Comment by mpociot** [comment] 2021-06-08 11:25
@danydev I thought that this issue was fixed by now.
Are you still experiencing this issue?

If you do, I would highly appreciate an easy-to-reproduce repository so that I can see how this can be fixed inside of Expose.

**Comment by danydev** [comment] 2021-06-08 11:28
Yes, it's still happening in 1.5.1. I'll try to create a mini-application in the next week or two, so you can actually reproduce it.

**Comment by sschlein** [comment] 2023-12-21 13:05
Closing this issue because it's old 🙈

**Closed by sschlein** 2023-12-21 13:05 UTC
