### ISSUE TITLE
Css/Js missing on Wordpress local site hosted with Valet Plus

### ISSUE THREAD

**Issue by iamlasse** [beyondcode/expose#43] opened 2020-06-18 14:06 UTC
I've tried sharing a locally installed Wordpress site with Valet Plus, the site loads but no assets are getting imported. All Css/Js come up Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure script '<URL>'. This request has been blocked; the content must be served over HTTPS. If I use expose share https:// the valet server can't find the site on :443?

**Comment by ahinkle** [comment] 2020-06-19 14:02
Duplicate of #19 , #33

**Comment by SamuelNitsche** [comment] 2020-06-19 15:33
This is an issue with wordpress, since wordpress tries to request all assets from the configured url.

**Comment by jeff-h** [comment] 2020-06-22 04:01
@iamlasse Is your site available locally via https? eg `https://mylocalurl.test`? If not, `expose` is likely serving your site at `https://something.sharedwithexpose.com` but the resource links inside the HTML will be to `http`, and your browser will throw the "Mixed Content" warning. Wordpress is going to need to build the HTML with all links being generated with `https://something.sharedwithexpose.com/*` instead of `http://mylocalurl.test/*`.

Of course I could be completely off base :)

**Comment by iamlasse** [comment] 2020-06-22 09:54
Yes I’m using valet plus and have done valet secure “mysite” on the site in question. But when trying to use https expose appends Port 440 on the url Which valet doesnt seem to recognize. And when i run regular expose then i get the mixed content http https issue.

**Comment by jeff-h** [comment] 2020-06-22 09:57
Port 440 is odd — you don't mean 443?

**Comment by bjaspire** [comment] 2020-07-04 14:50
It is not a good fit for WordPress because WordPress uses Absolute Paths. If you want to use then make 2 different database one is for local development environment and another is for this expose.
While making database for expose then replace all local paths to expose path on database.

**Comment by sschlein** [comment] 2023-12-21 13:04
Closing this issue because it's old 🙈

**Closed by sschlein** 2023-12-21 13:04 UTC
