### ISSUE TITLE
Running expose in Docker for another container fails

### ISSUE THREAD

**Issue by TiiFuchs** [beyondcode/expose#146] opened 2020-10-27 21:50 UTC
Hi,

I tried to run expose in a Docker container that is linked to a nginx webserver.
I ran `expose share nginx ...`. 
Note that "nginx" is the hostname of the container that serves the website and it is reachable via curl etc.

But expose cannot resolve the hostname "nginx", because in [app/Client/Http/HttpClient.php in line 69](https://github.com/beyondcode/expose/blob/538c7da446907a4f910275ae6ead98b39420cd71/app/Client/Http/HttpClient.php#L69) the dns ip is fixed as '127.0.0.1', which is not how it's configured in the Ubuntu system I ran expose on.

I found out that docker configured the dns to be 127.0.0.11 in /etc/resolv.conf, and when I changed this IP address in HttpClient.php to the correct one, everything worked fine.
I also tried to remove the DNS IP address and it worked too.

So I guess it should be removed...? So the DNS resolver of the system is beeing used.

**Comment by TiiFuchs** [comment] 2020-10-27 22:11
I created a pull request for this problem: #148

**Comment by dbpolito** [comment] 2021-02-16 21:29
This was fixed then reverted for some reason, so the bug is back on latest version, i added a comment on the PR that the regression was made:

https://github.com/beyondcode/expose/pull/177/files#r577150227

**Comment by sschlein** [comment] 2023-12-21 13:07
Closing this issue because it's old. Please feel free to open a new one if it's still relevant.

**Closed by sschlein** 2023-12-21 13:07 UTC
