### ISSUE TITLE
Loading users results in a timeout.

### ISSUE THREAD

**Issue by thomashondema** [beyondcode/expose#66] opened 2020-06-22 21:27 UTC
Both api (/api/users) and dashboard page (/users) fails while loading.
Standard composer installation with sqlite on php 7.4.3.
No errors appear in the logs also not with -vvv.

**Comment by mpociot** [comment] 2020-06-22 21:30
This is a duplicate of https://github.com/beyondcode/expose/issues/18
Make sure that you have configured the correct path to the database file

**Closed by mpociot** 2020-06-22 21:30 UTC
